### ISSUE TITLE
Newline issues in PDF

### ISSUE THREAD

**Issue by bitcoinhodler** [joaofnfernandes/glacierprotocol.github.io#7]
Many of the code boxes show both missing and extra newlines. These look correct on the HTML site but not in the PDF. Example:

![glacier-pdf-newline-issue](https://user-images.githubusercontent.com/31543633/40084796-db6d2c98-5887-11e8-955e-97f24d5333a7.png)

**Comment by bitcoinhodler** [comment]
I generated this pdf by running `make pdf` on a new instance of Ubuntu 14.04.

**Comment by joaofnfernandes** [comment]
Fixed via 60b3d59e0535c6dad2a26bf13ef3419ff3c26c8b

![screen shot 2018-05-16 at 10 20 28](https://user-images.githubusercontent.com/1525937/40132916-fd86811a-58f2-11e8-9243-0c5db128ce9f.png)

**Comment by bitcoinhodler** [comment]
Fixed? Eh? Your screenshot shows that it's still totally wack. That raw signed transaction should be one solid block of characters.

**Comment by joaofnfernandes** [comment]
Oh... for some reason I was assuming that the outline was multi-line, but now that I think of it it seems that the whole signed transaction is just a long single-line string that just wraps around.

@bitcoinhodler Would this solve it?

<img width="1277" alt="screen shot 2018-05-16 at 18 30 31" src="https://user-images.githubusercontent.com/1525937/40151943-abbfe84a-5937-11e8-823e-07c16d9977d6.png">

**Comment by bitcoinhodler** [comment]
That's still not correct. Look at the newlines around the first four lines. There are still both extra and missing newlines.

In this case they are arguably innocuous, but it worries me that it doesn't match exactly, because that means there may be many other places throughout the doc that are messed up. (This latest change doesn't seem to be pushed to the repo so I can't check for myself, but as of 18 hours ago there were still many, many code blocks with issues.)

**Comment by bitcoinhodler** [comment]
Also what has happened to the color highlights? The raw transaction should be highlighted as yellow, and the words "private keys" should be highlighted red.

**Comment by joaofnfernandes** [comment]
Fixed via ebec4735e98ddce2b2073d87efcfe5ef8c75c4c0.
As I said, there are a couple of snippets where the text is too long, so it needs to wrap to the next line.

When wrapping, the place where you'll see the line breaking will necessarily be different because the font size is different and the space to render the text is different too.
